name: sprinternship-project

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api:/app/api
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/api/rdu-sprinternship-2025-ee7f24ebcd45.json

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/public:/app/frontend/public
      - ./frontend/src:/app/frontend/src
      
      - ./frontend/Dockerfile:/app/frontend/Dockerfile
      
      - ./frontend/eslint.config.js:/app/frontend/eslint.config.js
      
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/vite.config.js:/app/frontend/vite.config.js
    ports:
      - '5173:5173'
    env_file:
      - .env

  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3305:3306"
    env_file:
      - .env
    volumes:
      - "./database/db_schema:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
